// Own astronomical geometry; no Adhan, calendar files, city lookup or network.
import { solarCoordinatesUSNO } from '../../../core/astronomy/solar-usno-v2.mjs';
import { solarCoordinatesNoaa } from '../../../core/astronomy/noaa-coordinates.mjs';
import { findLevelCrossings } from '../../../core/astronomy/continuous-solver.mjs';

const DAY = 86400000, HOUR = 3600000, MINUTE = 60000, RAD = Math.PI / 180;
const SOURCE = 'https://fiqhcouncil.org/the-suggested-calculation-method-for-fajr-and-isha/';
export const PROFILES = Object.freeze({
  'fcna-usa-15': Object.freeze({ id: 'fcna-usa-15', geographicalScope: 'FCNA recommendation for USA', fajrAngle: 15, ishaAngle: 15, source: SOURCE }),
  'fcna-canada-13': Object.freeze({ id: 'fcna-canada-13', geographicalScope: 'FCNA recommendation for Canada', fajrAngle: 13, ishaAngle: 13, source: SOURCE }),
});
const REQUIRED = ['startDate', 'latitude', 'longitude', 'timeZone', 'profileId'];
const OPTIONAL = ['endDate', 'asr'];
const EVENTS = ['fajr', 'sunrise', 'dhuhr', 'asr', 'maghrib', 'isha'];
const isoDate = epoch => new Date(epoch).toISOString().slice(0, 10);
const parseDate = date => {
  if (typeof date !== 'string' || !/^20\d{2}-\d{2}-\d{2}$/.test(date)) throw new RangeError('Date must be YYYY-MM-DD in 2000–2099');
  const epoch = Date.parse(`${date}T00:00:00Z`);
  if (!Number.isFinite(epoch) || isoDate(epoch) !== date) throw new RangeError('Invalid Gregorian date');
  return epoch;
};
function ownData(input, required, optional = []) {
  if (!input || Object.getPrototypeOf(input) !== Object.prototype) throw new TypeError('Plain own-data object required');
  const descriptors = Object.getOwnPropertyDescriptors(input), keys = Reflect.ownKeys(descriptors);
  if (required.some(k => !Object.hasOwn(descriptors, k)) || keys.some(k => typeof k !== 'string' || ![...required, ...optional].includes(k))) throw new TypeError('Missing or unknown field');
  if (keys.some(k => !Object.hasOwn(descriptors[k], 'value') || !descriptors[k].enumerable)) throw new TypeError('Enumerable own data fields only; no accessors');
}
function formatter(timeZone) {
  if (typeof timeZone !== 'string' || (timeZone !== 'UTC' && !timeZone.includes('/'))) throw new RangeError('Explicit IANA timezone required');
  return new Intl.DateTimeFormat('en-GB-u-ca-gregory-nu-latn', { timeZone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23', timeZoneName: 'longOffset' });
}
function civil(epoch, fmt) {
  const p = Object.fromEntries(fmt.formatToParts(epoch).filter(p => p.type !== 'literal').map(p => [p.type, p.value]));
  const offset = p.timeZoneName === 'GMT' ? '+00:00' : p.timeZoneName.replace('GMT', '');
  if (!/^[+-]\d{2}:\d{2}$/.test(offset)) throw new Error('Unsupported historical sub-minute timezone offset');
  const localDate = `${p.year}-${p.month}-${p.day}`, time = `${p.hour}:${p.minute}`;
  return { localDate, time, localIso: `${localDate}T${time}:00${offset}`, utc: new Date(epoch).toISOString() };
}

function geometry(dateEpoch, latitude, longitude, profile, asrFactor, fmt, ephemeris) {
  const coordinates = ephemeris === 'noaa' ? solarCoordinatesNoaa : solarCoordinatesUSNO;
  const at = epoch => coordinates(epoch / DAY + 2440587.5);
  const altitude = epoch => {
    const solar = at(epoch), utcHours = ((epoch % DAY) + DAY) % DAY / HOUR;
    const hourAngle = (utcHours + longitude / 15 + solar.equationOfTimeHours - 12) * 15 * RAD;
    const sine = Math.sin(latitude * RAD) * Math.sin(solar.declination * RAD) + Math.cos(latitude * RAD) * Math.cos(solar.declination * RAD) * Math.cos(hourAngle);
    return Math.asin(Math.max(-1, Math.min(1, sine))) / RAD;
  };
  let carrier = dateEpoch, transit;
  for (let attempt = 0; attempt < 4; attempt++) {
    transit = carrier + (12 - longitude / 15) * HOUR;
    for (let step = 0; step < 12; step++) transit = carrier + (12 - longitude / 15 - at(transit).equationOfTimeHours) * HOUR;
    const actualDate = civil(transit, fmt).localDate;
    if (actualDate === isoDate(dateEpoch)) break;
    if (attempt === 3) throw new Error('Requested civil date has no matching solar transit; possibly skipped by timezone');
    // The internal carrier may cross the public 2000/2099 range boundary.
    // `actualDate` is generated by Intl, not user input.
    carrier += dateEpoch - Date.parse(`${actualDate}T00:00:00Z`);
  }
  const startEpoch = transit - 12 * HOUR, endEpoch = transit + 12 * HOUR;
  const diagnostic = threshold => findLevelCrossings({ startEpoch, endEpoch, valueAt: epoch => altitude(epoch) - threshold });
  const horizon = diagnostic(-50 / 60), fajr = diagnostic(-profile.fajrAngle), isha = profile.ishaAngle === profile.fajrAngle ? fajr : diagnostic(-profile.ishaAngle);
  const select = (result, direction, before) => {
    const crossings = result.crossings.filter(c => c.direction === direction && (before ? c.epoch <= transit : c.epoch >= transit));
    return crossings.length === 1 ? { rawEpoch: crossings[0].epoch, reason: null } : { rawEpoch: null, reason: crossings.length > 1 ? 'multiple-crossings-not-resolved' : result.status === 'crossings' ? 'no-crossing-on-required-side-of-transit' : result.status };
  };
  let asr;
  const zenithDistanceAtTransit = Math.abs(latitude - at(transit).declination);
  if (zenithDistanceAtTransit >= 90 || altitude(transit) <= 0) {
    asr = { rawEpoch: null, reason: 'no-positive-sun-height-at-transit' };
  } else {
    const asrResult = findLevelCrossings({ startEpoch: transit, endEpoch, valueAt: epoch => {
      const zenith = Math.abs(latitude - at(epoch).declination);
      if (zenith >= 90) return NaN;
      const target = Math.atan(1 / (asrFactor + Math.tan(zenith * RAD))) / RAD;
      return target > 0 ? altitude(epoch) - target : NaN;
    } });
    asr = select(asrResult, 'setting', false);
  }
  return {
    solarCalculationDate: isoDate(carrier), transit,
    raw: { fajr: select(fajr, 'rising', true), sunrise: select(horizon, 'rising', true), dhuhr: { rawEpoch: transit, reason: null }, asr, maghrib: select(horizon, 'setting', false), isha: select(isha, 'setting', false) },
  };
}

/** Diagnostic-only implementations of source angles and explicit auxiliary geometry. */
export function calculateOwnFcna(options, configuration) {
  ownData(options, REQUIRED, OPTIONAL);
  ownData(configuration, ['ephemeris', 'rounding']);
  if (!['usno', 'noaa'].includes(configuration.ephemeris) || !['nearest', 'ceil'].includes(configuration.rounding)) throw new RangeError('Unknown declared numerical candidate');
  const { startDate, endDate = startDate, latitude, longitude, timeZone, profileId, asr = 'standard' } = options;
  if (typeof profileId !== 'string' || !Object.hasOwn(PROFILES, profileId)) throw new RangeError('Explicit FCNA profile required');
  if (!['standard', 'hanafi'].includes(asr)) throw new RangeError('Explicit supported Asr convention required');
  if (!Number.isFinite(latitude) || Math.abs(latitude) > 90 || !Number.isFinite(longitude) || Math.abs(longitude) > 180) throw new RangeError('Finite geographic coordinates required');
  const start = parseDate(startDate), end = parseDate(endDate);
  if (end < start || end - start >= 366 * DAY) throw new RangeError('Range must contain 1–366 days');
  const fmt = formatter(timeZone), profile = PROFILES[profileId], days = [];
  const round = configuration.rounding === 'nearest' ? Math.round : Math.ceil;
  for (let epoch = start; epoch <= end; epoch += DAY) {
    const date = isoDate(epoch), raw = geometry(epoch, latitude, longitude, profile, asr === 'hanafi' ? 2 : 1, fmt, configuration.ephemeris);
    const events = Object.fromEntries(EVENTS.map(event => {
      const { rawEpoch, reason } = raw.raw[event];
      if (rawEpoch === null) return [event, { status: 'unavailable', time: null, utc: null, localDate: null, localIso: null, reason, highLatitudeFallback: null }];
      const rounded = round(rawEpoch / MINUTE) * MINUTE;
      return [event, { status: 'calculated-experimental', ...civil(rounded, fmt), rawUtc: new Date(rawEpoch).toISOString(), basis: ['fajr', 'isha'].includes(event) ? 'FCNA-source-angle-with-independent-astronomy' : 'auxiliary-astronomical-convention-not-specified-by-FCNA-source' }];
    }));
    days.push({ date, solarCalculationDate: raw.solarCalculationDate, events });
  }
  return {
    schemaVersion: 1, profile: { ...profile, version: '0.1.0-own-research', officialImplementationApproved: false },
    location: { latitude, longitude, timeZone }, range: { startDate, endDate, dayCount: days.length },
    engine: { name: `own-${configuration.ephemeris}-continuous-spherical`, version: '0.1.0', tzdb: process.versions.tz, rounding: configuration.rounding, horizonDegrees: -50 / 60, asrFactor: asr === 'hanafi' ? 2 : 1, timeArgument: 'UTC Julian date, following published approximation; no separate TT correction', geometry: 'Geocentric solar centre and conventional horizon; no topocentric parallax, terrain or elevation correction' },
    productionReady: false, notificationEligible: false,
    limitations: ['FCNA prescribes these Fajr/Isha angle approximations, not this six-event numerical engine or its rounding.', 'No claim that every US or Canadian mosque uses the selected profile; no country or school inferred from coordinates.', 'Missing crossings remain unavailable; no high-latitude replacement has been invented.', 'Dhuhr is unshifted astronomical transit; other auxiliary events and separately selected Asr are not institution-confirmed prayer specifications.', 'Optional observational caution recommended by FCNA is not converted into unverified fixed minutes.', 'Astronomical cycle is attached by solar transit to the requested civil day; local event dates are retained explicitly.'],
    days,
  };
}
