// Replay behavior statistics from retained calculation outputs; no network needed.
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {analyzeRows} from './analyze.mjs';

const root=fileURLToPath(new URL('../../',import.meta.url));
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const data='core/local/verification/oss-relative/';
const sources=[
  {id:'go-prayer-v1.1.1',input:data+'go-prayer-v1.1.1-2026-2028.jsonl.gz',years:[2026,2027,2028],
    commit:'02a763f9afd0eba1d93489bd9a47370695aba44b',repository:'https://github.com/hablullah/go-prayer',
    metadata:'scripts/oss-relative/go/metadata.json'},
  {id:'mawaqit-v0.5.0',input:data+'mawaqit-v0.5.0-2026-2028.jsonl.gz',years:[2026,2027,2028],
    commit:'aa31f98b0128e54c936b6e8e37841102ce90d454',repository:'https://github.com/sniper1720/mawaqit',
    metadata:data+'mawaqit-metadata.json'},
  {id:'mawaqit-v0.4.0',input:data+'mawaqit-v0.4.0-2027.jsonl.gz',years:[2027],
    commit:'50f18017317a6858058fb8734a68fd415073f5e7',repository:'https://github.com/sniper1720/mawaqit',
    metadata:data+'mawaqit-metadata.json'},
];

export async function buildReport(){
  const implementations=[];
  for(const source of sources){
    const compressed=await readFile(resolve(root,source.input)),bytes=gunzipSync(compressed);
    const rows=bytes.toString().trim().split('\n').map(line=>JSON.parse(line));
    implementations.push({...source,compressedSha256:sha(compressed),outputSha256:sha(bytes),
      metadataSha256:sha(await readFile(resolve(root,source.metadata))),analysis:analyzeRows(rows,{years:source.years})});
  }
  const harnesses={};
  for(const folder of ['go','mawaqit']){
    const prefix=`scripts/oss-relative/${folder}/`;
    for(const name of (await readdir(resolve(root,prefix),{recursive:true})).sort()){
      if(/(?:\.rs|\.go|\.mod|\.sum|Cargo\.toml|Cargo\.lock)$/.test(name)){
        harnesses[prefix+name]=sha(await readFile(resolve(root,prefix,name)));
      }
    }
  }
  return{result:'REPLAYED',limits:'Behavior comparison only. The retained outputs are generated by third-party software, not observed or official prayer calendars. No accuracy ranking or Diyanet equivalence.',
    configuration:'MWL 18/17, Asr factor 1, LocalRelativeEstimation; exact configuration/toolchain and time/date conventions in linked metadata and harness documentation.',
    implementations,harnesses,analyzerSha256:sha(await readFile(new URL('./analyze.mjs',import.meta.url))),
    runnerSha256:sha(await readFile(fileURLToPath(import.meta.url)))};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){
  const report=await buildReport();
  await writeFile(resolve(root,'core/local/verification/oss-relative-2026-09-27.json'),JSON.stringify(report,null,2)+'\n');
  console.log(JSON.stringify(report.implementations.map(({id,analysis:a})=>({id,days:a.plannedDays,
    complete:a.groups.reduce((n,g)=>n+g.completeDays,0),errors:a.groups.reduce((n,g)=>n+g.errorDays,0),
    order:a.groups.reduce((n,g)=>n+g.withinDayOrderViolations,0),crossNight:a.groups.reduce((n,g)=>n+g.crossNightViolations,0),
    largestPhaseSeconds:Object.fromEntries(['fajr','isha'].map(name=>[name,Math.max(...a.groups.map(g=>g.changes[name].maximumAbsoluteSeconds))]))})),null,2));
}
